# This official base image contains node.js and npm
FROM node:10
ARG VERSION=1.0.0
WORKDIR c:\\project\\weather-service\\src\\app

# Copy the application files
COPY src\\package.json src\\app.js c:\\project\\weather-service\\src
COPY src\\lib c:\\project\\weather-service\\src\\app\\lib

# Download the required packages for production
RUN npm install

# Make the application run when running the container
EXPOSE 8080
CMD [ "node", "server.js" ]

